### ISSUE TITLE
Container command '/opt/open-ocr/open-ocr-httpd' not found or does not exist. Ubuntu 15.10

### ISSUE THREAD

**Issue by FBurner** [tleyden/open-ocr#63] opened 2016-05-28 11:49 UTC
Hi,

Im getting **"Container command '/opt/open-ocr/open-ocr-httpd' not found or does not exist."** on

**sudo docker-compose up**

on ubuntu 15.10

**Comment by tleyden** [comment] 2016-06-01 17:05
Can you post the full logs of your docker compose output?

**Comment by tleyden** [comment] 2016-09-21 18:55
Seems to be a duplicate of https://github.com/tleyden/open-ocr/issues/66, but I have no idea how to reproduce this.

**Closed by tleyden** 2016-09-21 18:55 UTC
